version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    environment:
      - APP_SETTINGS=config.Config
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=5000
    links:
      - db
    ports:
      - "5000:5000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
